### ISSUE TITLE
Slider returning to initial value on reactivation

### ISSUE THREAD

**Issue by Racafe92** [WaveEngine/MixedRealityToolkit-WaveEngine#5]
Hello

I have found a problem when I disable and re-enable a slider I have already changed. 
The slider does not save it previous value, but it resets to the "initial value". I don't know if this is a desired behaviour or a bug.

Steps to reproduce:
- Create a scene with a slider and a button to disable/enable the slider
- Slide the thumb to a extreme
- Disable the slider and enable it
- The slider will seem to be in the correct position (in the extreme) but when you try to move the thumb, you will find out that it will jump directly to the initial position

In my project, I have been able to fix it setting in the "onActivate" event the "value" directly but I think this should be something to be fixed here

**Comment by minolo** [comment]
Thanks for your report! This should be fixed in the next release.
